<a href="https://colab.research.google.com/github/prathiksha061/Day-2/blob/main/Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lists

In [48]:
movies = ["Soorarai Pottru","Thani Oruvan","Mudhalvan","with love","Interstellar"]
print(movies[0], movies[-1])

movies.append("RRR")
movies.pop(1)
print(movies)

movies.sort()
print(movies)

print(len(movies))
print("Interstellar" in movies)

Soorarai Pottru Interstellar
['Soorarai Pottru', 'Mudhalvan', 'with love', 'Interstellar', 'RRR']
['Interstellar', 'Mudhalvan', 'RRR', 'Soorarai Pottru', 'with love']
5
True


Tuples

In [49]:
city = ("Chennai", "Coimbatore", "Trichy", "Madurai", "Salem")
print(city[1], city[3])

Coimbatore Madurai


In [50]:
city [1] ="banglore"


TypeError: 'tuple' object does not support item assignment

Basically in tuple we cannot change value , it is immutable.

In [51]:
a, b, c, d, e = city
print(a, b, c, d, e)

Chennai Coimbatore Trichy Madurai Salem


In [52]:
l = list(city)
l.append("Pune")
city= tuple(l)
print(city)

('Chennai', 'Coimbatore', 'Trichy', 'Madurai', 'Salem', 'Pune')


 Dictionary

In [53]:
# 1
student = {"name": "Prathiksha", "age": 19, "grade": "A", "city": "Trichy"}
print(student.keys())
print(student.values())
print(student.items())

dict_keys(['name', 'age', 'grade', 'city'])
dict_values(['Prathiksha', 19, 'A', 'Trichy'])
dict_items([('name', 'Prathiksha'), ('age', 19), ('grade', 'A'), ('city', 'Trichy')])


In [54]:
student["grade"] = "O"
student["email"] = "xxxxxxx@gmail.com"
del student["city"]
print(student)

{'name': 'Prathiksha', 'age': 19, 'grade': 'O', 'email': 'xxxxxxx@gmail.com'}


Set

In [55]:
week = {"Math", "Physics", "Chemistry"}
weekend = {"Computer", "English", "Math"}
print(week | weekend)
print(week & weekend)
print(week - weekend)

{'English', 'Physics', 'Chemistry', 'Computer', 'Math'}
{'Math'}
{'Chemistry', 'Physics'}


In [56]:
week.add("Tamil")
weekend.remove("English")
print(week,weekend)

{'Chemistry', 'Math', 'Physics', 'Tamil'} {'Computer', 'Math'}


In [57]:
print("Math" in week or "Math" in weekend)

True


Functions

In [58]:
def greet(name):
    print(f"Hello, {name}! Welcome to Day 2.")

greet("Suvalakshmi")

Hello, Suvalakshmi! Welcome to Day 2.


In [59]:
def add_numbers(a, b):
    return a + b
add_numbers (2,3)

5

In [60]:
def find_max(a, b, c):
    return max(a, b, c)

find_max(10,15,12)

15

In [61]:
def is_even(n):
    return n % 2 == 0

is_even(9)

False

Default Parameters

In [62]:
def introduce(name, language="Python"):
    print(f"{name} is learning {language}")

introduce("Suva")
introduce("Suva", "SQL")

Suva is learning Python
Suva is learning SQL


In [63]:
def calculate_discount(price, discount=10):
    return price - (price * discount / 100)

print(calculate_discount(100))
print(calculate_discount(110,15))

90.0
93.5


if / else

In [64]:
n = int(input("enter a no "))
if n > 0:
    print("Positive")
elif n < 0:
    print("Negative")
else:
    print("Zero")

enter a no 50
Positive


In [65]:
score = int(input("enter your score : "))
if score >= 90:
    print("A")
elif score >= 80:
    print("B")
elif score >= 70:
    print("C")
elif score >= 60:
    print("D")
else:
    print("F")

enter your score : 90
A


In [66]:
year = int(input())
if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:
    print("It is a Leap Year")
else:
    print("It is Not a Leap Year")

2026
It is Not a Leap Year


For Loop

In [67]:
for i in range(1, 21):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [68]:
for i in range(2, 51, 2):
    print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [69]:
fruits = ["apple", "banana", "cherry"]
for i in range(len(fruits)):
    print(i, fruits[i])

0 apple
1 banana
2 cherry


In [70]:
sum =  0
for i in range(1, 101):
    sum += i
print(sum)

5050


In [71]:
x = "hello"
count = 0
for letter in x:
    if letter in "aeiou":
        count += 1
print(count)

2


NumPy

In [72]:
import numpy as np

In [73]:
a = np.array([10, 20, 30, 40, 50])
print(a)

[10 20 30 40 50]


In [74]:
print(np.zeros(10))
print(np.ones(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [75]:
print(np.arange(1, 21))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [76]:
print(np.linspace(0, 1, 7))

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [77]:
print(np.random.randint(1, 101, 8))

[12 64 82 13 27  5 56 97]


Task 2

In [78]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [79]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [80]:
print(np.full((4, 4), 7))

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [81]:
print(np.random.rand(3, 4))

[[0.64295702 0.77263134 0.1360408  0.99745897]
 [0.43607093 0.11189488 0.3797149  0.8613436 ]
 [0.263473   0.59056219 0.86017299 0.95180589]]


In [82]:
print(np.array([[1,2,3],[4,5,6],[7,8,9]]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Task3

In [83]:
x = np.random.randint(1,10,(4,5))

print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)
print(x.itemsize)
print(x.nbytes)

2
(4, 5)
20
int64
8
160


In [84]:
y= np.array([1,2,3,4])

print(y.ndim)
print(y.shape)
print(y.size)
print(y.dtype)
print(y.itemsize)
print(y.nbytes)


1
(4,)
4
int64
8
32


Task 4

In [85]:
a = np.array([1,2,3])
print(a.dtype)

int64


In [86]:
b = np.array([1.5,2.0,3.6])
print(b.dtype )

float64


In [87]:
c= np.array([1,2,3])
print(c)
print(c.astype(float))

[1 2 3]
[1. 2. 3.]


In [88]:
d= np.array([1,2.5,3])
print(d.dtype)

float64


In [89]:
e= np.array(["a","b","c"], dtype=str)
print(e.dtype)

<U1


Task5

In [90]:
a= np.zeros(10)
a[5] = 99
print(a)

[ 0.  0.  0.  0.  0. 99.  0.  0.  0.  0.]


In [91]:
print(np.arange(0, 51, 5))

[ 0  5 10 15 20 25 30 35 40 45 50]


In [92]:
a= np.eye(5)
print(np.diag(a))

[1. 1. 1. 1. 1.]


In [93]:
 a= np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [94]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [ ]:
Task 6

In [95]:
a = np.arange(1,16)

print(a[:5])
print(a[-3:])
print(a[::2])

[1 2 3 4 5]
[13 14 15]
[ 1  3  5  7  9 11 13 15]


In [96]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(b[1,2])
print(b[1])
print(b[:,2])

6
[4 5 6]
[3 6 9]


Task 7

In [97]:
a= np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]


In [98]:
a= np.arange(1,11)
print(a*3)

[ 3  6  9 12 15 18 21 24 27 30]


In [100]:
a= np.array([4,9,16,25,36])
print(np.sqrt(a))

[2. 3. 4. 5. 6.]


In [101]:
a=np.array([1,2,3,4,5])

print(a.sum())
print(a.mean())
print(a.min())
print(a.max())

15
3.0
1
5


In [102]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a.sum(axis=1))

[ 6 15 24]


In [103]:
print(a.sum(axis=0))

[12 15 18]
